stages:
  - test

variables:
  POETRY_VIRTUALENVS_CREATE: "false"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv
    - ~/.cache/pypoetry
    - ~/.cache/pip

unit_tests:
  stage: test
  image: python:3.9
  tags:
    - feature  # tag que seu runner suporta
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry install --no-root
  script:
    - pytest tests/
  only:
    - /^feature\/.*$/

integration_test:
  stage: test
  image: python:3.12
  tags:
    - release  # tag do runner para releases
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry install --no-root
  script:
    - python src/main.py
  only:
    - release

skip_main:
  stage: test
  tags:
    - ci  # qualquer tag registrada serve
  script:
    - echo "Nada é executado na main"
  only:
    - main
